# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0002_remove_vendedorambprofile_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorambprofile',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='acme.Product'),
        ),
    ]
