# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acme', '0002_auto_20170525_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorAmbProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
