# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acme', '0002_remove_product_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
