# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0002_auto_20170526_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(default='acme/img/AvatarEstudiante.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='vendedorambprofile',
            name='avatar',
            field=models.ImageField(default='acme/img/AvatarVendedor4.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='avatar',
            field=models.ImageField(default='acme/img/AvatarVendedor1.png', upload_to=b''),
        ),
    ]
