# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0003_product_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendedor',
        ),
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
