# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0003_product_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorambprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='acme.ClientProfile'),
        ),
        migrations.AddField(
            model_name='vendedorfijoprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='acme.ClientProfile'),
        ),
    ]
