# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0003_product_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedorambprofile',
            name='cash',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='cash',
            field=models.BooleanField(),
        ),
    ]
