# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0003_auto_20170525_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='ClientProfile',
        ),
    ]
