# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0003_auto_20170526_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedorambprofile',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='acme.Product'),
        ),
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='acme.Product'),
        ),
    ]
