# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0004_auto_20170526_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedorambprofile',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='vendedorfijoprofile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='favVendAmb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.VendedorAmbProfile'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='favVendFijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.VendedorFijoProfile'),
        ),
    ]
