# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0004_auto_20170528_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedorambprofile',
            name='cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='cash',
            field=models.BooleanField(default=True),
        ),
    ]
