# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0005_product_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avatar',
            new_name='photo',
        ),
    ]
