# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0005_vendedorfijoprofile_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='dishes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.Product'),
        ),
    ]
