# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0005_auto_20170528_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedorambprofile',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
