# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0006_auto_20170529_0836'),
        ('acme', '0006_auto_20170528_2312'),
    ]

    operations = [
    ]
