# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0007_auto_20170526_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedorfijoprofile',
            name='dishes',
        ),
        migrations.AddField(
            model_name='vendedorfijoprofile',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedorfijoprofile',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedorfijoprofile',
            name='debit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedorfijoprofile',
            name='juna',
            field=models.BooleanField(default=False),
        ),
    ]
