# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0008_auto_20170526_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorambprofile',
            name='cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedorambprofile',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedorambprofile',
            name='debit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedorambprofile',
            name='juna',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendedorfijoprofile',
            name='cash',
            field=models.BooleanField(default=True),
        ),
    ]
