# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0009_auto_20170526_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedorambprofile',
            old_name='juna',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='vendedorfijoprofile',
            old_name='juna',
            new_name='student',
        ),
    ]
