# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0010_auto_20170526_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorfijoprofile',
            name='dishes',
            field=models.ManyToManyField(to='acme.Product'),
        ),
    ]
